---
name: "test-plz"

on:
  push:
    branches:
      - "mainline"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "mainline"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - id: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 1
      - name: "test"
        run: "make test"
